# Generated by Django 3.0.9 on 2022-05-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('objective', models.TextField(blank=True)),
                ('startYear', models.CharField(max_length=4)),
                ('endYear', models.CharField(blank=True, max_length=4)),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=40)),
                ('degreeType', models.CharField(blank=True, max_length=50)),
                ('gpa', models.CharField(blank=True, max_length=4)),
                ('schoolextra', models.CharField(blank=True, max_length=300)),
                ('jobStartYear', models.CharField(max_length=10)),
                ('jobTitle', models.CharField(max_length=40)),
                ('jobEndYear', models.CharField(blank=True, max_length=10)),
                ('employer', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('awards', models.CharField(blank=True, max_length=500)),
                ('extraC', models.CharField(blank=True, max_length=1000)),
                ('projectName', models.CharField(blank=True, max_length=100)),
                ('projectDesc', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
