# Generated by Django 4.0.3 on 2022-03-26 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.CharField(max_length=4)),
                ('endYear', models.CharField(max_length=4)),
                ('school', models.CharField(max_length=100)),
                ('gpa', models.FloatField()),
                ('academAchieve', models.CharField(max_length=300)),
                ('jobStartYear', models.DateField()),
                ('jobEndYear', models.DateField()),
                ('employerName', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=500)),
                ('awards', models.CharField(max_length=500)),
                ('extraCariculars', models.CharField(max_length=1000)),
                ('projectName', models.CharField(max_length=100)),
                ('projectDesc', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
